# These are supported funding model platforms

github: [BunsDev]
patreon: BunsDev
# open_collective: # Replace with a single Open Collective username
ko_fi: bunsdev
# tidelift: npm/create-markdown
custom: ['https://dedevs.club']
